fix: install isomorphic-unfetch
On an empty installation it cannot run because it says

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'isomorphic-unfetch'
Require stack:
- /klabot/node_modules/discord-music-player/dist/utils/Utils.js
- /klabot/node_modules/discord-music-player/dist/index.js
- /klabot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/klabot/node_modules/discord-music-player/dist/utils/Utils.js:8:46)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/klabot/node_modules/discord-music-player/dist/utils/Utils.js',
    '/klabot/node_modules/discord-music-player/dist/index.js',
    '/klabot/index.js'
  ]
}

I fix this by adding isomorphic-unfetch as discord-music-player asks.